### ISSUE TITLE
Branching strategy for supporting multiple versions of Ansible

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#103]
As seen in #100, we will eventually be in a future where Ansible 2.1 is old and Ansible 2.2 will be the default installed on all the new hosts.

I wonder if a potential solution is to maintain multiple branches of the code, one for each version of Ansible we decide to support.  I'd say initially we would have two branches:  `ansible_2_1` and `ansible_2_2`

Would like to hear what other folks think about this idea.

**Comment by mike-nguyen** [comment]
Two branches would provide the cleanest separation if we want to have callback_plugins for 2.1 and 2.2 as suggested in #100.  

Perhaps we should try to see what kind of failures there are running on 2.2 and evaluate how much work it would be to update the test to be compatible with 2.2 versus maintaining two branches?

**Comment by miabbott** [comment]
> Perhaps we should try to see what kind of failures there are running on 2.2 and evaluate how much work it would be to update the test to be compatible with 2.2 versus maintaining two branches?

Yeah, this would be a smart starting point.

**Comment by miabbott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Create two branches fo [a-h-t] to track Ansible versions](https://trello.com/c/Gnu20TZg/683-2-create-two-branches-fo-a-h-t-to-track-ansible-versions)

**Comment by jlebon** [comment]
Hmm, could we not just require a virtualenv? Having branches sounds like it could get tedious fast. (E.g. we'd have to backport fixes, improvements, and new tests to both branches, right?). OTOH, if we make it clear that we require the Ansible version in `requirements.txt`, then we can bump the version and accomodate the playbooks/plugins at our pace, without affecting users & automated testers.

**Comment by miabbott** [comment]
@dustymabe Can you comment on this issue?  Your experience was the origin for this idea.

**Comment by dustymabe** [comment]
i personally think that we should support both in a single branch - i guess I would be interested to know how hard we think that would be to do.

**Comment by mike-nguyen** [comment]
I started a preliminary investigation into updating the tests to run on 2.2.  Surprisingly there is very little to change in order to get our test to run on 2.2.  The callback plugin will need to be reworked and we have 4 instances where we use a soon-to-be-deprecated docker module.  There are also a minor tweak to one task in the runc test.  

The only test that is really affected is k8-cluster which has roles that user the docker module.  I think it would be adequate to test that scenario across the different atomic host streams.

**Comment by miabbott** [comment]
If the migration path to 2.2 is that easy, then we should just head in that direction.

The only caveat is notifying any users (which should be few) about the change.

**Comment by miabbott** [comment]
We decided to move to Ansible 2.2 entirely.  This was enabled with #100
