### ISSUE TITLE
Run the openshift-ansible installer on unstable streams

### ISSUE THREAD

**Issue by jlebon** [projectatomic/atomic-host-tests#131]
As a complement to https://github.com/openshift/openshift-ansible/pull/3890, it would be great to start testing unstable streams against stable tagged releases. That way, we can tell if an update in the host breaks Origin.

**Comment by miabbott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Run the stable OpenShift Ansible installer as an [a-h-t] test on unstable streams](https://trello.com/c/Tk1Hs17D/725-5-run-the-stable-openshift-ansible-installer-as-an-a-h-t-test-on-unstable-streams)

**Comment by miabbott** [comment]
Closing this via #162
