### ISSUE TITLE
Special case Fedora 26 selinux context for /usr/bin/docker-storage-setup

### ISSUE THREAD

**Issue by mike-nguyen** [projectatomic/atomic-host-tests#133]
Container-storage-setup is used in F26 which makes /usr/bin/docker-storage-setup a symlink with the selinux context of system_u:object_r:bin_t:s0.  Dan Walsh said "docker-storage-setup is a symbolic link to container-storage-setup So bin_t is fine."

The selinux_verify role currently checks for container_runtime_exec_t so there needs to be a special case for Fedora 26.

**Comment by mike-nguyen** [comment]
Additional comments from Dan in #atomic:

"We had a label of docker* for files, which is why it was container_runtime_exec_t, now it is a lnk_file so it defaults back to bin_t, but neither has any effect"

**Comment by miabbott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Fix SELinux context test in [a-h-t] to properly support F26](https://trello.com/c/q9BtvI8O/724-3-fix-selinux-context-test-in-a-h-t-to-properly-support-f26)
