### ISSUE TITLE
check that non-root user can run rpm-ostree status

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomic-host-tests#134]
See https://github.com/projectatomic/rpm-ostree/issues/738

Would be nice to add a test for that. Would probably need to include:

- create a new user
- switch to that user and try to show status

**Comment by miabbott** [comment]
We could probably test this by just dropping `become` privileges as part of a role and running `rpm-ostree status`

**Comment by miabbott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Add test to [a-h-t] to verify non-root users can use 'rpm-ostree status'](https://trello.com/c/LoGB1stD/723-2-add-test-to-a-h-t-to-verify-non-root-users-can-use-rpm-ostree-status)
