### ISSUE TITLE
consider adding retry logic to operations that require external networks

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#156]
We've seen failures in the tests due to connection timeouts or abrupt resets of connections when the tests are doing things like `atomic pull` or `docker pull`

We might be able to workaround some of these transient failures by just using the `retries` parameter in the roles.

Example:

```
- name: Pull busybox
  command: atomic pull busybox
  register: pull
  retries: 6
  delay: 30
  until: pull.rc == 0
```

**Comment by mike-nguyen** [comment]
Definitely needed!

**Comment by miabbott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(2) Enhance [a-h-t] network roles to implement retries](https://trello.com/c/AVW7ZB4X/764-2-enhance-a-h-t-network-roles-to-implement-retries)

**Comment by miabbott** [comment]
A bunch of work was done in this space with #190, #193, and #195 

I think it is safe to close.
