### ISSUE TITLE
Verify docker storage persists across reboot

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/atomic-host-tests#166]
Let's make sure we don't hit [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1457912) again by adding a test for it in a-h-t. 

Can most likely be done as part of the work for https://github.com/projectatomic/atomic-host-tests/issues/121

**Comment by miabbott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Add [a-h-t] test case to verify default docker storage driver](https://trello.com/c/7e2MgiLb/711-3-add-a-h-t-test-case-to-verify-default-docker-storage-driver)
