### ISSUE TITLE
configure 'rpm-install' role to use different RPM

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#175]
Having to scrape a web page to determine the name of the `fpaste` RPM before installing is cumbersome and introduces more chances of failure.

@dustymabe suggested that we use the `epel-release` RPM which should have a static name based on the major version release.

https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

**Comment by dustymabe** [comment]
> @dustymabe suggested that we use the epel-release RPM which should have a static name based on the major version release.

correction - I think the url won't change, but the rpm that gets downloaded can have a different NEVR. i.e. today you could download an rpm from that link and it is epel-release-1.0.0 and tomorrow it could be epel-release-2.0.0. Make sense?

**Comment by miabbott** [comment]
FYI, even though the [EPEL](https://fedoraproject.org/wiki/EPEL) page points to dl.fp.o for the `epel-release` RPM, you can use download.fp.o and it works just as well.

https://download.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

**Comment by mike-nguyen** [comment]
@dustymabe do you know of another rpm that is like epel-release that has a constant URL?

**Comment by dustymabe** [comment]
> @dustymabe do you know of another rpm that is like epel-release that has a constant URL?

I don't. I think that one was special because they wanted to be able to have people pull it directly. This was before `epel-release` was in the base centos repos.

**Comment by mike-nguyen** [comment]
#177 Changes the rpm install for the improved sanity test.  Since there was no other case like epel-release, the admin-unlock test will continue to use the parsed html to find the correct file name from EPEL (this is now split into two roles).
