### ISSUE TITLE
add system container test to 'improved-sanity-test'

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#187]
I thought we were doing this already, but nope.

install, run, uninstall perhaps?

**Comment by miabbott** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=1461994 which we should have been able to catch

**Comment by miabbott** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Add system-container test to [a-h-t] sanity tests](https://trello.com/c/2wIUtlbZ/781-3-add-system-container-test-to-a-h-t-sanity-tests)

**Comment by miabbott** [comment]
We should aim to test a variety of system-containers, as we have seen different behaviors based on which container we pull ([bz 1451697](https://bugzilla.redhat.com/show_bug.cgi?id=1451697))

- `registry.access.redhat.com/openshift4/openshift-ansible`
- `registry.fedoraproject.org/f25/etcd`
- `registry.fedoraproject.org/f25/flannel`

**Comment by mike-nguyen** [comment]
#196 addresses the etcd scenario requested above.
