### ISSUE TITLE
add a kubernetes test to 'sanity' suite

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#200]
Our current set of tests in the 'sanity' suite does not include any kube tests.

We have separate test suites for Kube + OpenShift Origin, but they currently don't get run often enough to catch any regressions.

**Comment by miabbott** [comment]
Our internal Jenkins jobs are running the `k8-cluster` test after every successful sanity test, so I don't know if this card is still relevant.  Especially as we are moving away from having `kubernetes` on host for most of the platforms.

@mike-nguyen I think we can close this, WDYT?

**Comment by mike-nguyen** [comment]
Let's close it.
