### ISSUE TITLE
verify that all of our tests work with Python 3

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#287]
See this comment and related discussion - https://pagure.io/atomic-wg/issue/372#comment-483693

**Comment by miabbott** [comment]
Hit this issue almost immediately https://github.com/ansible/ansible-modules-core/issues/5840

Looks like it was fixed in Ansible 2.3, so I'm going to try running the tests using Python3 + Ansible 2.3

**Comment by mike-nguyen** [comment]
*crosses fingers* hopefully the tests run on 2.3.  Callback function may need some work.

**Comment by miabbott** [comment]
I ran almost all of the tests (except `openshift-ansible-test` and `unique-machine-id`) against an F27AH system with `-e ansible_python_interpreter=/usr/bin/python3` and using Python3 + Ansible 2.3 on my workstation.

All the tests worked as expected, which is great news.  I think I'm going to continue down this path and see if Ansible 2.4 works for us.

Additionally, it would probably be prudent to test using Ansible 2.3/2.4 with Python2, since most of the streams we test still default to that.

**Comment by miabbott** [comment]
Noting some deprecation warnings when using Ansible 2.4:

```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static 
 inclusions or 'include_tasks' for dynamic inclusions. This feature will be removed in a future release. 
 Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.              
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module  
documentation details page may explain more about this rationale.. This feature will be removed in a     
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in            
ansible.cfg.
```

**Comment by miabbott** [comment]
Hit this particular error when running the `rpm-ostree` test suite; specifically the `upgrade_rebase_install_uninstall` portion

`ERROR! Unexpected Exception, this is probably a bug: maximum recursion depth exceeded`

This was using Python3 + Ansible 2.4.2.0

I found the following issue which looks like it is fixed in Ansible 2.4.3

https://github.com/ansible/ansible/issues/23609

**Comment by miabbott** [comment]
To be ready for Python3, I see a couple of things we need to do:

- switch to Ansible 2.4.x (Ansible 2.4.0.0 for now, due to the above comment)
- stop using `include:` and start using `include_tasks:`

**Comment by miabbott** [comment]
I'm going to close this issue and open a separate one for migrating towards Python3 + Ansible 2.4
