### ISSUE TITLE
migrate from "yes/no" values to real boolean "true/false" types

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#299]
As part of #296, @ashcrow was quoting the `yes` and `no` values as that is proper YAML syntax.  Ansible is generous with their parsing and will automatically quote those values, so we were getting away with the unquoted usage.

To make things more compliant with the spec, we should change all the `yes/no` values to be real boolean `true/false` types.

**Comment by mike-nguyen** [comment]
This issue was fixed in #302
