### ISSUE TITLE
Make the k8-cluster test more generic

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#31]
While the reviews continue on #30, I wanted to capture what I found about using upstream containers for Fedora/CentOS.  

Google has a registry that has the necessary containers, but they don't tag their containers with `latest` like the rest of the world (AFAIK).

Based on the comment here https://github.com/kubernetes/kubernetes/issues/11751#issuecomment-163487575, you can `curl` a special URL that returns the latest stable release of the containers.  Then using that tag, you can pull the containers.

```
$ curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
v1.2.4
$ docker pull gcr.io/google_containers/kube-apiserver:v1.2.4
Trying to pull repository gcr.io/google_containers/kube-apiserver ... v1.2.4: Pulling from google_containers/kube-apiserver
52becac66096: Pull complete 
Digest: sha256:32901915205c4c3be4960638f8f6440b0c924d8d925ad18694db8e4f00036ed0
Status: Downloaded newer image for gcr.io/google_containers/kube-apiserver:v1.2.4
```

cc: @mnguyen-gh @jlebon

**Comment by mnguyen-gh** [comment]
The documentation example had me pull kubernetes-apiserver, kubernetes-controller-mgr, and kubernetes-scheduler generically without the registry in the beginning.  When I ran the playbook on Fedora/CentOS, it actually pulled from Google and would fail later.  From what I could find from google, it was because there was a version mismatch between kubectl running on atomic host and the kube containers.   When I pulled from the redhat registry it worked.

**Comment by miabbott** [comment]
I think it would be possible to tie the version of the containers to the version supported by `kubectl`.

For example, using the latest Fedora AH:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"ef1caba064de975387860175c3138aad432cf356", GitTreeState:"clean"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

I would expect that the `v1.2.0` tag would work with that version of `kubectl`

Also, just for reference...here's how you can search the Google registry and get a list of tags:

```
$ curl -k -s -X GET https://gcr.io/v2/google_containers/kube-apiserver/tags/list  | python -m json.tool
{
...
    "name": "google_containers/kube-apiserver",
    "tags": [
        "9680e782e08a1a1c94c656190011bd02",
        "v1.2.0",
        "v1.2.0-alpha.8",
        "v1.2.0-beta.0",
        "v1.2.0-beta.1",
        "v1.2.1",
        "v1.2.1-beta.0",
        "v1.2.2",
        "v1.2.2-beta.0",
        "v1.2.3",
        "v1.2.3-beta.0",
        "v1.2.4",
        "v1.2.4-beta.0",
        "v1.2.5-beta.0",
        "v1.3.0-alpha.0",
        "v1.3.0-alpha.1",
        "v1.3.0-alpha.2",
        "v1.3.0-alpha.3",
        "v1.3.0-alpha.4",
        "v1.3.0-alpha.5"
    ]
}

**Comment by mnguyen-gh** [comment]
I'll try it out and update the playbook so fedora and centos pull from google

**Comment by miabbott** [comment]
Honestly, I'd just get PR #30 finished and merged.  Then tackle this issue.

**Comment by mnguyen-gh** [comment]
Sounds good.

**Comment by miabbott** [comment]
We've done a lot of work to the `k8-cluster` test and it works reliably on the streams we are testing.  Going to close this.
