### ISSUE TITLE
create a test to verify GPG checking on 'rpm-ostree install'

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#349]
We have a manual test case internal to Red Hat that grabs an unsigned RPM, props up a yum repo with it, and validates that GPG checking is enforced.

We can do something similar with the `aht-dummy` RPM that exists in the repo.

1.  Grab RPM
2.  `createrepo_c` on a directory
3.  create `/etc/yum.repos.d/dummy.repo` with `gpgcheck=1`
4.  try to `rpm-ostree install` and confirm it fails
5.  change `gpgcheck=0`
6.  try to `rpm-ostree install` and confirm it succeeds

**Comment by mike-nguyen** [comment]
#367

**Comment by miabbott** [comment]
Closed via #367
