### ISSUE TITLE
handle disabling 'live-restore' for 'docker swarm' test across all versions

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#370]
Fedora 27/28 started enabling live-restore mode directly in the daemon via the `--live-restore` flag:

https://src.fedoraproject.org/rpms/docker/c/96d8356c75f3a78f445bbc570dd0c2172977030d?branch=master

We previously were disabling `live-restore` via `/etc/docker/daemon.json` and now we have to handle both cases.

**Comment by mike-nguyen** [comment]
Fixed in #371
