### ISSUE TITLE
Ensure all role variables are prefixed 

### ISSUE THREAD

**Issue by mike-nguyen** [projectatomic/atomic-host-tests#376]
The role variables should be prefixed and adhere to the openshift style guide [0].  Most of the roles already do this but I noticed some that don't.  I've run into issues using include_role where there are variable collisions that were resolved when using prefixed variable names.

[0] https://github.com/openshift/openshift-ansible/blob/master/docs/style_guide.adoc#Role-variables-MUST-have-a-prefix-of-atleast-3-characters-See.below.for.specific.naming.rules

**Comment by miabbott** [comment]
This looks like #224 

We should close one of these; I don't really care which one...

**Comment by mike-nguyen** [comment]
I'll close this one in favor of #224
