### ISSUE TITLE
Sanity check `oc cluster up` on streams that have OpenShift built-in

### ISSUE THREAD

**Issue by jlebon** [projectatomic/atomic-host-tests#407]
This would be a nice check to have for RHCOS.

**Comment by miabbott** [comment]
I think there was an idea to convert/migrate/adapt the ‘openshift-ansible`
test to do this.  One way or another, we should have this kind of test.

If folks think this would be useful, I can put in the sprint backlog and
pull it in soon.

**Comment by miabbott** [comment]
COREOS-51 in the Jira backlog

**Comment by miabbott** [comment]
In #424, I've added a basic `oc cluster up` for AH streams as a start.

We haven't had a lot of success running our tests against RHCOS via the internal Jenkins jobs, so I didn't try the RHCOS case for #424.  Once we get those jobs sorted out, I'll expand the test to include support for RHCOS.
