### ISSUE TITLE
Add link to list of packages on dashboard

### ISSUE THREAD

**Issue by jlebon** [projectatomic/atomic-host-tests#422]
The dashboard is awesome. It'd be great if we could add another column with a link to the list of package NEVRAs in the tested version to make it easier to find out which versions were included.

(Or maybe just running an `rpm -qa` as part of the i-s-t to let it show up in the test logs?).

**Comment by miabbott** [comment]
I missed this earlier...should be pretty easy to do a `ostree db list` as part of the provision/setup phase of our jobs to capture this.  The sanity test dashboard should be able to handle the extra column...I don't think we can fit in another column for the rest of the tests.
