### ISSUE TITLE
Use system containers for kubernetes cluster test

### ISSUE THREAD

**Issue by miabbott** [projectatomic/atomic-host-tests#76]
As mentioned in #73, we should move to using system containers in the [kubernetes cluster test](https://github.com/projectatomic/atomic-host-tests/tree/master/tests/k8-cluster).  I believe we only need the `etcd` system container, because the single-node cluster does not require `flannel`

**Comment by miabbott** [comment]
We might be able to combine this work with #31

**Comment by mike-nguyen** [comment]
Since only a few system containers exist currently, we might want to use both the etcd and flannel containers so we get more functional coverage for them.  I'm not sure if this will require any configuration changes int he k8-cluster tests besides replacing flannel.

**Comment by miabbott** [comment]
I think this is covered via #335.  Closing.
