### ISSUE TITLE
Need to use IP(s) rather than the hostname for reboot based tests

### ISSUE THREAD

**Issue by kushaldas** [projectatomic/atomic-host-tests#82]
Any test that requires a reboot, for example *pkg-layering* requires IP(s) rather than a short hostname, otherwise they fail after the reboot.

```
TASK [reboot : restart hosts] **************************************************
ok: [host1]
ok: [host2]

TASK [reboot : wait for hosts to come back up (inventory_hostname)] ************
fatal: [host2 -> localhost]: FAILED! => {"changed": false, "elapsed": 120, "failed": true, "msg": "Timeout when waiting for host2:22"}
fatal: [host1 -> localhost]: FAILED! => {"changed": false, "elapsed": 120, "failed": true, "msg": "Timeout when waiting for host1:22"}
	to retry, use: --limit @/home/kdas/tmp/gotun/atomic-host-tests/tests/admin-unlock/main.retry

PLAY RECAP *********************************************************************
host1                      : ok=25   changed=15   unreachable=0    failed=1   
host2                      : ok=25   changed=15   unreachable=0    failed=1   

 [WARNING]: Consider using get_url or uri module rather than running curl
 [WARNING]: Consider using yum, dnf or zypper module rather than running rpm
```

If we use the IP directly instead of *host1* or *host2*, then the tests pass successfully.

**Comment by jlebon** [comment]
Ahh heh, the `wait_for` module requires a resolvable hostname. We should probably use `{{ ansible_default_ipv4.address }}` instead of `{{ inventory_hostname }}`.

**Comment by miabbott** [comment]
I'd love to get a solution for this that works for all cases.   

We've gone around on this a few times (see #9, #23, #44) and we ultimately settled on the current implementation.

Using `inventory_hostname` is what is [recommended by Ansible](https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back)

Additionally, we run these tests regularly in an OpenStack environment and haven't had any issues.

That's not to say that there aren't better ways to do this, but I feel like we have tried a number of approaches before ending up here.

**Comment by jlebon** [comment]
Oh right, the OpenStack case is an issue. The nodes there have no concept of what their public IPs are. The reason this works in our OpenStack is because `inventory_hostname` is the same as the public IP.

I think the more "ansible-y" way to do this would be to use `ansible_host` instead of `inventory_hostname`. That's exactly what it's for: if the inventory hostname is an alias like the above, then users *have* to specify `ansible_host` as well. When there is no explicit `ansible_host` specified, the variable `{{ ansible_host }}` will just resolve to the inventory hostname, since it's assumed that it's resolvable.

**Comment by mike-nguyen** [comment]
As Micah mentioned about the previous issues, I vaguely remember having issues with ansible_host where it would be defined if we looked at the ansible facts, but Ansible would not pick up on it while running tasks.

**Comment by jlebon** [comment]
Ahh OK, I just saw this comment now: https://github.com/projectatomic/atomic-host-tests/pull/44#r75500571

But I'm confused by the above. Is it saying that `ansible_host` is sometimes not defined, or that it's defined but somehow wrong? Testing around here, I see it always defined (this is with v2.2).

**Comment by mike-nguyen** [comment]
My memory of the details is unclear.  I wish I had some old logs to look at.  @miabbott was not seeing the issue with ansible_host but I was.  He was running with the -i flag and I was using the /etc/ansible/host file.  When it was changed over to inventory_hostname both scenarios worked.
